In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-6.3888e+07,  8.5059e-43, -6.3889e+07],
        [ 8.5059e-43, -6.3897e+07,  8.5059e-43],
        [-6.3886e+07,  8.5059e-43, -6.3893e+07],
        [ 8.5059e-43, -6.3895e+07,  8.5059e-43],
        [-6.3895e+07,  8.5059e-43, -6.3894e+07]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.9541, 0.6308, 0.6599],
        [0.7604, 0.4359, 0.3016],
        [0.0310, 0.9613, 0.3390],
        [0.1132, 0.7164, 0.8591],
        [0.4749, 0.3875, 0.5111]])


In [5]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4048, -0.9481,  1.7460],
        [-0.1516,  0.9320, -1.1812],
        [ 1.3130, -0.2752, -0.0433],
        [ 1.8512,  0.6798,  1.6297],
        [-0.1820,  1.1475,  0.6981]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)
print(y)
print(x+y)

tensor([[0.2198, 0.2732, 0.2011],
        [0.8154, 0.2711, 0.3847],
        [0.9948, 0.8327, 0.4494],
        [0.4790, 0.8406, 0.3663],
        [0.1366, 0.1191, 0.1714]])
tensor([[-0.1850, -0.6749,  1.9471],
        [ 0.6639,  1.2031, -0.7965],
        [ 2.3078,  0.5575,  0.4061],
        [ 2.3302,  1.5204,  1.9961],
        [-0.0455,  1.2666,  0.8694]])


In [10]:
print(torch.add(x,y))

tensor([[-0.1850, -0.6749,  1.9471],
        [ 0.6639,  1.2031, -0.7965],
        [ 2.3078,  0.5575,  0.4061],
        [ 2.3302,  1.5204,  1.9961],
        [-0.0455,  1.2666,  0.8694]])


In [11]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.1850, -0.6749,  1.9471],
        [ 0.6639,  1.2031, -0.7965],
        [ 2.3078,  0.5575,  0.4061],
        [ 2.3302,  1.5204,  1.9961],
        [-0.0455,  1.2666,  0.8694]])


In [12]:
y.add_(x)
print(y)

tensor([[-0.1850, -0.6749,  1.9471],
        [ 0.6639,  1.2031, -0.7965],
        [ 2.3078,  0.5575,  0.4061],
        [ 2.3302,  1.5204,  1.9961],
        [-0.0455,  1.2666,  0.8694]])


In [14]:
print(y[:,1])

tensor([-0.6749,  1.2031,  0.5575,  1.5204,  1.2666])


In [15]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8248])
-0.8248313069343567


In [17]:
import numpy as np

In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))